# Bayiler listesi
bayiler_listesi = [
    "DIRMAN ELEKT-I.DIRMAN/S.DIRMAN VE A.CAKMAK ADI ORTAKLIGI",
    "GOKNUR ELEKTRONIK ILETIS. MAK. OTOM. LTD.STI.",
    "HAKMAR ELK. ELEKT. ROLE SAN. TIC.LTD. STI.",
    "MAKS OTOM. MUH.VE ELKT. SAN. TIC.LTD. STI.",
    "MAS OTOM. ELK. ELKTR. BILG.YAZ. HIZ.MAK.IML.SAN VE TIC.LTD.STI.",
    "MAT OTO. END. ELK. ELKTR. GIDA ve MAK.SAN. LTD.STI.",
    "METE ELK. ELEKTR. OTOM. SIST.",
    "OKSITEM OTOM. KONT. SIST. ELEK. ELEKTR. END. MAK. TAAH. TIC. LTD. STI.",
    "SAKARYA CERAN MAK.OTOM.ELK. SAN.VE TIC.LTD.STI.",
    "TEKNOGRAT OTOM.VE ELK.ELKT. SAN.VE TIC.LTD.STI.",
    "UNAL OTOMASYON SAN. VE TIC.LTD.STI.",
    "ELSIS ELEKTRIK A.S.",
    "OZDE OTOMASYON",
    "SAMURTEK OTOM.ELK.ELKTR.MAK. SAN.TIC.LTD.STI.",
    "GOKNUR ELEKTRONIK ILETIS. MAK. OTOM. LTD.STI. GAZIANTEP SUBE",
    "HAKMAR ELK. ELEKT. ROLE SAN. TIC.LTD. STI. CERKEZKOY SUBE",
    "MAKS OTOM. MUH.VE ELKT. SAN. TIC.LTD. STI. BURSA SUBE",
    "MAT OTO. END. ELK. ELKTR. GIDA ve MAK.SAN. LTD.STI. KONYA SUBE"
]

# Telefon, faks ve adres bilgileri
telefonlar = {
    "DIRMAN ELEKT-I.DIRMAN/S.DIRMAN VE A.CAKMAK ADI ORTAKLIGI": "0242 334 77 25",
    "GOKNUR ELEKTRONIK ILETIS. MAK. OTOM. LTD.STI.": "0344 236 66 55",
    "HAKMAR ELK. ELEKT. ROLE SAN. TIC.LTD. STI.": "0212 238 60 85",
    "MAKS OTOM. MUH.VE ELKT. SAN. TIC.LTD. STI.": "0212 220 42 48",
    "MAS OTOM. ELK. ELKTR. BILG.YAZ. HIZ.MAK.IML.SAN VE TIC.LTD.STI.": "0258 241 43 48",
    "MAT OTO. END. ELK. ELKTR. GIDA ve MAK.SAN. LTD.STI.": "0338 224 16 50",
    "METE ELK. ELEKTR. OTOM. SIST.": "0352 322 19 10",
    "OKSITEM OTOM. KONT. SIST. ELEK. ELEKTR. END. MAK. TAAH. TIC. LTD. STI.": "0312 394 64 30",
    "SAKARYA CERAN MAK.OTOM.ELK. SAN.VE TIC.LTD.STI.": "0264 276 84 84 / 0276 44 51-52",
    "TEKNOGRAT OTOM.VE ELK.ELKT. SAN.VE TIC.LTD.STI.": "0232 459 00 66",
    "UNAL OTOMASYON SAN. VE TIC.LTD.STI.": "0322 882 02 05",
    "ELSIS ELEKTRIK A.S.": "0216 466 98 03",
    "OZDE OTOMASYON": "0232 782 32 75",
    "SAMURTEK OTOM.ELK.ELKTR.MAK. SAN.TIC.LTD.STI.": "0332 606 08 00 ",
    "GOKNUR ELEKTRONIK ILETIS. MAK. OTOM. LTD.STI. GAZIANTEP SUBE": "0342 337 41 78",
    "HAKMAR ELK. ELEKT. ROLE SAN. TIC.LTD. STI. CERKEZKOY SUBE": "0282 726 61 67",
    "MAKS OTOM. MUH.VE ELKT. SAN. TIC.LTD. STI. BURSA SUBE": "0224 443 57 81",
    "MAT OTO. END. ELK. ELKTR. GIDA ve MAK.SAN. LTD.STI. KONYA SUBE": "0332 346 58 58"
}
fakslar = {
    "DIRMAN ELEKT-I.DIRMAN/S.DIRMAN VE A.CAKMAK ADI ORTAKLIGI": "0242 334 77 54",
    "GOKNUR ELEKTRONIK ILETIS. MAK. OTOM. LTD.STI.": "0344 236 37 77",
    "HAKMAR ELK. ELEKT. ROLE SAN. TIC.LTD. STI.": "0212 297 08 57",
    "MAKS OTOM. MUH.VE ELKT. SAN. TIC.LTD. STI.": "0212 220 43 49",
    "MAS OTOM. ELK. ELKTR. BILG.YAZ. HIZ.MAK.IML.SAN VE TIC.LTD.STI.": "0258 261 90 76",
    "MAT OTO. END. ELK. ELKTR. GIDA ve MAK.SAN. LTD.STI.": "0338 224 16 51",
    "METE ELK. ELEKTR. OTOM. SIST.": "0352 322 19 13",
    "OKSITEM OTOM. KONT. SIST. ELEK. ELEKTR. END. MAK. TAAH. TIC. LTD. STI.": "0312 394 63 50",
    "SAKARYA CERAN MAK.OTOM.ELK. SAN.VE TIC.LTD.STI.": "0264 276 44 45",
    "TEKNOGRAT OTOM.VE ELK.ELKT. SAN.VE TIC.LTD.STI.": "0232 373 77 67",
    "UNAL OTOMASYON SAN. VE TIC.LTD.STI.": "0322 882 01 15",
    "ELSIS ELEKTRIK A.S.": "0216 466 98 59",
    "OZDE OTOMASYON": "0232 782 32 75",
    "SAMURTEK OTOM.ELK.ELKTR.MAK. SAN.TIC.LTD.STI.": "0332 606 08 00",
    "GOKNUR ELEKTRONIK ILETIS. MAK. OTOM. LTD.STI. GAZIANTEP SUBE": "-",
    "HAKMAR ELK. ELEKT. ROLE SAN. TIC.LTD. STI. CERKEZKOY SUBE": "0282 726 61 68",
    "MAKS OTOM. MUH.VE ELKT. SAN. TIC.LTD. STI. BURSA SUBE": "0224 443 57 92",
    "MAT OTO. END. ELK. ELKTR. GIDA ve MAK.SAN. LTD.STI. KONYA SUBE": "0332 346 58 59"
}

adresler = {
    "DIRMAN ELEKT-I.DIRMAN/S.DIRMAN VE A.CAKMAK ADI ORTAKLIGI": "KEPEZ MAH. YESIL ANTALYA SAN. SIT. 3189/8 SOK. NO:2, KEPEZ / ANTALYA",
    "GOKNUR ELEKTRONIK ILETIS. MAK. OTOM. LTD.STI.": "YAVUZ SELIM MH. M.NURI ARIKAN CD. NO:81/A KAHRAMANMARAS",
    "HAKMAR ELK. ELEKT. ROLE SAN. TIC.LTD. STI.": "OKCUMUSA CD. MENEVSE IS MERKEZI NO:22 DUKKAN NO:88 KARAKOY / ISTANBUL",
    "MAKS OTOM. MUH.VE ELKT. SAN. TIC.LTD. STI.": "IKITELLI OSB MAH.BEDRETTIN DALAN BLV. NO:23 IC KAPI NO:25 BASAKSEHIR / ISTANBUL",
    "MAS OTOM. ELK. ELKTR. BILG.YAZ. HIZ.MAK.IML.SAN VE TIC.LTD.STI.": "AHI SINAN CD. SARAYLAR MH. NO:30 MERKEZEFENDI / DENIZLI",
    "MAT OTO. END. ELK. ELKTR. GIDA ve MAK.SAN. LTD.STI.": "O.S.B. 1.CD. NO:6 KARAMAN",
    "METE ELK. ELEKTR. OTOM. SIST.": "O.S.B. 29.CD. NO:59 MELIKGAZI / KAYSERI",
    "OKSITEM OTOM. KONT. SIST. ELEK. ELEKTR. END. MAK. TAAH. TIC. LTD. STI.": "HAS EMEK SAN. SIT. 1463. CD. NO:28 IVEDIK OSB. YENIMAHALLE / ANKARA",
    "SAKARYA CERAN MAK.OTOM.ELK. SAN.VE TIC.LTD.STI.": "GUNEY MOBILYACILAR SAN. SIT. 1294.SK.NO:14, ERENLER / SAKARYA",
    "TEKNOGRAT OTOM.VE ELK.ELKT. SAN.VE TIC.LTD.STI.": "1203/9 SOK. NO:3/N YENISEHIR GIDA CARSISI HASANATLI IS MRK., KONAK / IZMIR",
    "UNAL OTOMASYON SAN. VE TIC.LTD.STI.": "YESIL OBA MAH. 46257 SOK.OTO SAN.SIT. S-BLOK NO:7/18 Z08, SEYHAN / ADANA",
    "ELSIS ELEKTRIK A.S.": "ESENSEHIR MAH. ATILIM SOKAK NO:19/B GIRIŞ KAT UMRANIYE / ISTANBUL",
    "OZDE OTOMASYON": "KASIMPASA MAH. 50.YIL CAD. NO:13/4A, MENDERES / IZMIR",
    "SAMURTEK OTOM.ELK.ELKTR.MAK. SAN.TIC.LTD.STI.": "FEVZICAKMAK, MEDCEZIR CD. KAPI NO:27A, 42050 KARATAY / KONYA",
    "GOKNUR ELEKTRONIK ILETIS. MAK. OTOM. LTD.STI. GAZIANTEP SUBE": "1. O.S.B 83120 NOLU CD. NO:14 BASPINAR, SEHITKAMIL / GAZIANTEP",
    "HAKMAR ELK. ELEKT. ROLE SAN. TIC.LTD. STI. CERKEZKOY SUBE": "FEVZIPASA MAH.MEMUR SOK.SUMLU APT. NO:20/22A, CERKEZKOY / TEKIRDAG",
    "MAKS OTOM. MUH.VE ELKT. SAN. TIC.LTD. STI. BURSA SUBE": "ALAADDIN BEY MH.636 SK. SARP PLAZA NO:5, NILUFER / BURSA",
    "MAT OTO. END. ELK. ELKTR. GIDA ve MAK.SAN. LTD.STI. KONYA SUBE": "FEVZICAKMAK MAH. MODESA MOB. SITESI 10742 SOKAK NO:1 KARATAY / KONYA"
}

# E-posta adresleri
email_adresleri = {
    "DIRMAN ELEKT-I.DIRMAN/S.DIRMAN VE A.CAKMAK ADI ORTAKLIGI": "info@dirman.com",
    "GOKNUR ELEKTRONIK ILETIS. MAK. OTOM. LTD.STI.": "",
    "HAKMAR ELK. ELEKT. ROLE SAN. TIC.LTD. STI.": "",
    "MAKS OTOM. MUH.VE ELKT. SAN. TIC.LTD. STI.": "",
    "MAS OTOM. ELK. ELKTR. BILG.YAZ. HIZ.MAK.IML.SAN VE TIC.LTD.STI.": "",
    "MAT OTO. END. ELK. ELKTR. GIDA ve MAK.SAN. LTD.STI.": "",
    "METE ELK. ELEKTR. OTOM. SIST.": "",
    "OKSITEM OTOM. KONT. SIST. ELEK. ELEKTR. END. MAK. TAAH. TIC. LTD. STI.": "",
    "SAKARYA CERAN MAK.OTOM.ELK. SAN.VE TIC.LTD.STI.": "",
    "TEKNOGRAT OTOM.VE ELK.ELKT. SAN.VE TIC.LTD.STI.": "",
    "UNAL OTOMASYON SAN. VE TIC.LTD.STI.": "",
    "ELSIS ELEKTRIK A.S.": "",
    "OZDE OTOMASYON": "",
    "SAMURTEK OTOM.ELK.ELKTR.MAK. SAN.TIC.LTD.STI.": "",
    "GOKNUR ELEKTRONIK ILETIS. MAK. OTOM. LTD.STI. GAZIANTEP SUBE": "",
    "HAKMAR ELK. ELEKT. ROLE SAN. TIC.LTD. STI. CERKEZKOY SUBE": "",
    "MAKS OTOM. MUH.VE ELKT. SAN. TIC.LTD. STI. BURSA SUBE": "",
    "MAT OTO. END. ELK. ELKTR. GIDA ve MAK.SAN. LTD.STI. KONYA SUBE": ""
}